### ISSUE TITLE
[BUG] Typo in "future meetups"

### ISSUE THREAD

**Issue by IvoPereira** [CharlieBrownCharacter/feedback#17]
**Describe the bug**
Seeing "Looks like you don't have any feature meetups."

**To Reproduce**
1. Go to https://codotto.com/dashboard
2. See error

**Expected behavior**
See "Looks like you don't have any future meetups. "

**Screenshots**
![image](https://user-images.githubusercontent.com/1396475/169654004-29594d95-6373-491d-b2a5-e37af4f30fa4.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 100

**Additional context**
N/A

**Comment by CharlieBrownCharacter** [comment]
Thank you @IvoPereira for the report. We will fix this right away :)

**Comment by CharlieBrownCharacter** [comment]
@IvoPereira Fixed :)
