### ISSUE TITLE
[FEATURE]: Slides

### ISSUE THREAD

**Issue by silvenon** [CharlieBrownCharacter/feedback#20]
**Is your feature request related to a problem? Please describe.**
Yes, as a speaker I want to attach slides to my talk after the meetup in a way that would notify attendees (on Meetup.com I do this via comments).

**Describe the solution you'd like**
A way to attach a link to my slides on my talk that would notify attendees of that particular meetup, so that people could click on the link called "Slides" next to my talk (or something like that). It would be great if the link to the slides was also prominent in the email itself, so that people don't have to visit Codotto just to find the link to my slides, but instead click on the link in the email directly.

In my case I host my talks on Speaker Deck, I think that's what everyone can do instead of implementing file hosting on Codotto which would be a lot more work.

**Describe alternatives you've considered**
No alternatives AFAIK.

**Additional context**
Suggestion:

<img width="767" alt="Screenshot 2022-10-26 at 22 02 51" src="https://user-images.githubusercontent.com/471278/198125927-2ef9d2bf-c9c2-4b69-a6bd-459f1fdf128b.png">

**Comment by CharlieBrownCharacter** [comment]
Hey @silvenon . We apologize for the time it took to actually answer this but to be honest we completely missed the notification for the new issue created.

We currently have the field "Presentation" when you are on the page to update (or create) your talk

**Comment by silvenon** [comment]
Oh, I missed it! That works fine 👌 Hopefully the members who attended the meetup get the email notification that slides have been attached. If not, that's my suggestion for discoverability.
