### ISSUE TITLE
[FEATURE] Speaker feedback

### ISSUE THREAD

**Issue by silvenon** [CharlieBrownCharacter/feedback#21]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but something that would make Codotto stand out is a way for the attendees to provide direct anonymous feedback to speakers. (Like Filip did to me in person.)

**Describe the solution you'd like**
Instead of the generic email requesting for rating and feedback that Meetup.com sends to attendees after meetups, Codotto could send an email that offers a way to send feedback to speakers directly (as well as the organization team).

**Describe alternatives you've considered**
People could unsubscribe from such emails, though, but at least they will find out about this feature and know that they can provide it on the web if they want to. I haven't really thought this through, though.

**Additional context**
This is the email Meetup.com sends, but it's not really valuable and people don't even know that they will be able to write feedback to the organizers if they decide to rate it.

<img width="407" alt="Screenshot 2022-10-28 at 15 27 16" src="https://user-images.githubusercontent.com/471278/198609875-37d826e9-e86b-4868-9a36-925198346090.png">

**Comment by CharlieBrownCharacter** [comment]
@silvenon First, let me thank you for taking the time to write such a detailed feature request. We always enjoy receiving these requests to improve codotto :)

This feature is an excellent request and funny enough, it is something we are currently working on. Now, this is the way it goes:

1. Attendees go to a meetup
2. Attendee receives an email to rate the meetup AND rate the speakers of the meetup
3. After the attendee leaves feedback, the organizer of the meetup will be able to see the feedback for the meetup and the talks

As you could see from the flow, nowhere the speaker will be able to see his feedback and that is something that we have not considered but luckily you pointed that one out. We will see if we will include your suggestion (make it possible for the speaker to see his ratings and feedback) within the release of the first version of the feedback system or we will create a new improvement card for it, but rest assured that this will be implemented as it will greatly improve how the community can interact with each other.

I will leave this issue OPEN for the next few days in case you would like to add some more info or comment on something I have said.

Let us know what you think :smiley:

**Comment by silvenon** [comment]
These things are very delicate, so I'm sure you'll figure it out better than me. I like where you're going, it makes a lot of sense to me and I'm excited about it, because it might help improve meetups.

From where you left off you could continue perhaps so that organizers can optionally pick certain feedbacks they deem useful and forward them to the speakers they are intended for with a simple click of a button. That way sounds best to me because filtering useless and painful feedback can be done by the people who won't be hurt by it (that is, depending on how terrible the feedback is phrased).

Looking forward to this feature either way!
