### ISSUE TITLE
[FEATURE] Allow speakers of talks to be invited and not automatically invite him

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [CharlieBrownCharacter/feedback#6]
**Is your feature request related to a problem? Please describe.**
Currently when you create a `meetup`, you are allowed to add a speaker to your `meetup`. 

The problem is that I can add anyone that I would like. This leads to problems where I'm being added to meetups that I'm not going to speaker. 

**Describe the solution you'd like**
It would be nice to have a system where instead of automatically adding someone to the meetup you would first invite this person, then the speaker either could accept or deny being a speaker. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by FiKapusta** [comment]
I agree with the solution. Also, both the organizer and speaker should have notifications when one of the above happens.

**Comment by CharlieBrownCharacter** [comment]
@FiKapusta good suggestions. Then something like:

1. I create a meetup
2. I invite you to be a speaker in my meetup
3. You get a notification letting you know that you have been invited to speak 
4. You can either accept or deny the invitation
5. If you accept the invitation you are confirmed as a spaker to the meetup
6. If you deny the invitation, the organizer can't invite you again

There are some edge cases where if you deny first, the meetup organizer won't be able to invite you again but I think that for now it should be simple like that.

Will start working on it today. If you would like to see some changes, feel free to comment and we can discuss them.

**Comment by CharlieBrownCharacter** [comment]
@FiKapusta The feature has been implemented. You will notice that when you create a `meetup` and invites someone to your meetup to be a speaker, the speaker will receive a notification. The speaker can `accept` or `deny` the invitation. You, as the organizer of the meetup won't receive a notification when the user `accepts` or `deny` the invitation.

Currently we are trying to understand which notifications are important to our users. Please, feel free to leave feedback here (or open a new issue) if you think that this notification is necessary.

Thank you for contributing :)
